Fix git builds against Qt 5.14
Summary:
It's not really acceptable to just error on everything since some of the
solutions (like in this case) might not be retrocompatible.

The error was:
kdecoration/src/decoration.cpp:386:37: error: no member named 'posF' in 'QWheelEvent'

Test Plan: Builds now

Reviewers: #frameworks, vkrause

Reviewed By: vkrause

Subscribers: plasma-devel

Tags: #plasma

Differential Revision: https://phabricator.kde.org/D25671